projectOne/oneApp/urls.py
from django.urls import path
from . import views

app_name = 'oneApp'

urlpatterns = [
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('user_register/', views.user_register, name='user_register'),
]

projectOne/projectOne/urls.py
from django.contrib import admin
from django.urls import path, include
from oneApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('oneApp/', include('oneApp.urls'))
]

projectOne/oneApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

projectOne/oneApp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from django.forms.widgets import Select

class ProfileForm(forms.ModelForm):
    email = forms.CharField(widget=forms.EmailInput(
        attrs={
            'class':'form-control', 'placeholder':'example@email.com', 'required':'True'
        }
    ))
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control', 'placeholder':'Username', 'required':'True'
        }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class':'form-control', 'placeholder':'Password', 'required':'True'
        }
    ))

    class Meta():
        model = User
        fields = ('email', 'username', 'password')

projectOne/oneApp/views.py
from django.shortcuts import render
from .forms import ProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

# Create your views here.
def index(request):
    return render(request, 'oneApp/index.html')

@login_required
def user_logout(request):
    logout(request)
    return render(request, 'oneApp/index.html', {})


def user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return render(request, 'oneApp/index.html', {'user':user, 'username':username})

            else:
                return render(request, 'oneApp/index.html', {})
        else:
            values = True
            return render(request, 'oneApp/user_login.html', {'values':values})

    else:
        return render(request, 'oneApp/user_login.html', {})

def user_register(request):

    errorit = False
    register = False

    if request.method == 'POST':
        user_form = ProfileForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            username = request.POST.get('username')
            register = True

        else:
            errorit = True

    else:
        user_form = ProfileForm()


    return render(request, 'oneApp/user_register.html', {'register':register, 'user_form': user_form, 'errorit': errorit})

projectOne/oneApp/templates/oneApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% block title %}
      <title>Base title</title>
    {% endblock title %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/general.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">CREAD</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="#">Posts</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          </ul>
        </div>

        {% if user.is_authenticated %}
          <ul class="navbar-nav">
            <li class="nav-item active"><a class="nav-link" href="{% url 'oneApp:user_logout' %}">LogOut</a></li>
            <li class="nav-item active nav-link collapse navbar-collapse">{{ username }}</li>
          </ul>
        {% else %}
          <ul class="navbar-nav">
            <li class="nav-item active"><a class="nav-link" href="{% url 'oneApp:user_login' %}">Login</a></li>
            <li class="nav-item active collapse navbar-collapse"><a class="nav-link" href="{% url 'oneApp:user_register' %}">SignUp</a></li>
          </ul>
        {% endif %}

      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

projectOne/oneApp/templates/oneApp/index.html
{% extends 'oneApp/base.html' %}
{% load static %}
{% block title %}
  <title>HOME</title>
{% endblock title %}

{% block body_block %}
  {% if user.is_authenticated %}
    <div class="general_content jumbotron">
      <h1 class="align_center">WELCOME! {{ username }}</h1>
      <h3 class="align_center">Want to publish a post?</h3>
      <button class="btn btn-outline-warning giveMarginTop" type="button" name="button">Publish Now!</button>
    </div>
  {% else %}
    <div class="general_content jumbotron">
      <h1 class="align_center">WELCOME!</h1>
      <h3 class="align_center">To publish a post you must be loged in!</h3>
    </div>
  {% endif %}
{% endblock %}

projectOne/oneApp/templates/oneApp/user_login.html
{% extends 'oneApp/base.html' %}

{% block title %}
  <title>LOGIN</title>
{% endblock title %}

{% block body_block %}
  <div class="jumbotron general_content">
    <div class="giveMarginBottom">
      <h3>Log In</h3>
    </div>
    <form class="" action="{% url 'oneApp:user_login' %}" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" placeholder="Username" name='username' required>
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" placeholder="Password" name='password' required>
      </div>
      <button type="submit" class="btn btn-primary giveMarginTop">Log In</button>
      {% if values %}
        <p class="giveMarginTop">Incorrect Values! Try Again!</p>
      {% else %}
        <p class="giveMarginTop">Do not have an account? <a href="{% url 'oneApp:user_register' %}">Sign Up</a></p>
      {% endif %}
    </form>
  </div>
{% endblock %}

projectOne/oneApp/templates/oneApp/user_register.html
{% extends 'oneApp/base.html' %}

{% block title %}
  <title>LOGIN</title>
{% endblock title %}

{% block body_block %}
  <div class="jumbotron general_content">
    <div class="giveMarginBottom">
      <h3>Register</h3>
    </div>
    <form class="" action="{% url 'oneApp:user_register' %}" method="POST">
      {% csrf_token %}
      {{ user_form.as_p }}
      <button type="submit" class="btn btn-outline-warning giveMarginTop">Sign Up</button>
    </form>
    {% if register %}
      <p class="giveMarginTop">Registration Successfull! Now Try to Login.</p>
    {% endif %}
    {% if errorit %}
      <p class="giveMarginTop">Invalid Data! Try Again</p>
    {% endif %}
  </div>
{% endblock %}